config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles, except: :index do 
    collection do
      get :element
    end
  end
  # root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many_attached :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  def element
    
  end
  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to root_path, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :body, photos: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render "shared/banner" %>

<section>
<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<br>
<%= link_to "ELEMENT PAGE", element_articles_path %>
</section>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', root_path %>

app/views/articles/show.html.erb
<div class="show">

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Photo:</strong>
  <% if @article.photos.attached?%>
    <% @article.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog666g</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f4215bdb65.js" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render "shared/navbar" %>
  
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div id="banner">
  <div class="group">
    <h2>Vous ne savez pas ou partir ? Parfait !</h2>
    <div class="banner-group-link">
      <h2><%= link_to"Je suis flexible",  "#" %></h2>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar">
    <div class="first-element">
        <%= link_to root_path do %>
            <i class="fab fa-airbnb"></i>
        <% end %>
    </div>
    <div class="first-group">
        <h2><%= link_to "Hébergements", "#" %></h2>
        <h2><%= link_to "Experiences", "#" %></h2>
        <h2><%= link_to "Experiences en ligne", "#" %></h2>
    </div>
    <div class="second-group">
        <h2><%= link_to "Devenez hote", "#" %></h2>
        <%= link_to "#" do %>
            <i class="fas fa-globe"></i>
        <% end %>
        <div class="group">
            <%= link_to "#" do %>
                <i class="fas fa-bars"></i>
                <i class="fas fa-user-circle"></i>
            <% end %>
        </div>
    </div>
</div>